var VERSES = {
  es: [
    { text: 'No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia.', ref: 'Isaías 41:10' },
    { text: 'Jehová es mi pastor; nada me faltará. En lugares de delicados pastos me hará descansar; junto a aguas de reposo me pastoreará.', ref: 'Salmos 23:1-2' },
    { text: 'Todo lo puedo en Cristo que me fortalece.', ref: 'Filipenses 4:13' },
    { text: 'Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.', ref: 'Filipenses 4:7' },
    { text: 'Jehová es mi luz y mi salvación; ¿a quién temeré? Jehová es la fortaleza de mi vida; ¿de quién me he de atemorizarme?', ref: 'Salmos 27:1' },
    { text: 'Fíate de Jehová con todo tu corazón, y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, y él enderezará tus veredas.', ref: 'Proverbios 3:5-6' },
    { text: 'El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece; no hace nada indebido, no busca lo suyo, no se irrita, no guarda rencor.', ref: '1 Corintios 13:4-5' },
    { text: 'Tu palabra es una lámpara que guía mis pies y una luz para mi camino.', ref: 'Salmos 119:105' },
    { text: 'Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.', ref: 'Mateo 6:33' },
    { text: 'Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree no se pierda, mas tenga vida eterna.', ref: 'Juan 3:16' },
    { text: 'Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre sino por mí.', ref: 'Juan 14:6' },
    { text: 'El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente. Diré yo a Jehová: Esperanza mía y castillo mío; mi Dios, en quien confiaré.', ref: 'Salmos 91:1-2' },
    { text: 'Humillaos, pues, bajo la poderosa mano de Dios, para que él os exalte cuando fuere tiempo.', ref: '1 Pedro 5:6' },
    { text: 'Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.', ref: '1 Pedro 5:7' },
    { text: 'Fui joven, y ya soy viejo, y no he visto justo desamparado, ni su descendencia que mendigue pan.', ref: 'Salmos 37:25' },
    { text: 'Estad quietos y conoced que yo soy Dios; seré exaltado entre las naciones; enaltecido seré en la tierra.', ref: 'Salmos 46:10' },
    { text: 'Mas para Dios todo es posible.', ref: 'Mateo 19:26' },
    { text: 'Jehová tu Dios está en medio de ti, poderoso, él salvará; se gozará sobre ti con alegría, callará de amor, se regocijará sobre ti con cánticos.', ref: 'Sofonías 3:17' },
    { text: 'Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas.', ref: 'Josué 1:9' },
    { text: '¿Qué, pues, diremos a esto? Si Dios es por nosotros, ¿quién contra nosotros?', ref: 'Romanos 8:31' },
    { text: 'Estando persuadido de esto, que el que comenzó en vosotros la buena obra, la perfeccionará hasta el día de Jesucristo.', ref: 'Filipenses 1:6' },
    { text: 'Aguarda a Jehová; esfuérzate, y aliéntese tu corazón; sí, espera a Jehová.', ref: 'Salmos 27:14' },
    { text: 'Torre fuerte es el nombre de Jehová; a él correrá el justo y será levantado.', ref: 'Proverbios 18:10' },
    { text: 'Misericordioso y clemente es Jehová; lento para la ira, y grande en misericordia.', ref: 'Salmos 103:8' },
    { text: 'Pero los que esperan en Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán y no se cansarán; caminarán y no se fatigarán.', ref: 'Isaías 40:31' },
    { text: 'Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios.', ref: 'Mateo 5:9' },
    { text: 'Jehová peleará por vosotros, y vosotros estaréis tranquilos.', ref: 'Éxodo 14:14' },
    { text: 'Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús.', ref: '1 Tesalonicenses 5:18' },
    { text: 'Y conoceréis la verdad, y la verdad os hará libres.', ref: 'Juan 8:32' },
    { text: 'Así que, no os afanéis por el día de mañana, porque el día de mañana traerá su afán. Basta a cada día su propio mal.', ref: 'Mateo 6:34' }
  ],
  en: [
    { text: 'Fear not, for I am with you; be not dismayed, for I am your God. I will strengthen you, yes, I will help you, I will uphold you with My righteous right hand.', ref: 'Isaiah 41:10' },
    { text: 'The Lord is my shepherd; I shall not want. He makes me to lie down in green pastures; He leads me beside the still waters.', ref: 'Psalm 23:1-2' },
    { text: 'I can do all things through Christ who strengthens me.', ref: 'Philippians 4:13' },
    { text: 'And the peace of God, which surpasses all understanding, will guard your hearts and minds through Christ Jesus.', ref: 'Philippians 4:7' },
    { text: 'The Lord is my light and my salvation; whom shall I fear? The Lord is the strength of my life; of whom shall I be afraid?', ref: 'Psalm 27:1' },
    { text: 'Trust in the Lord with all your heart, and lean not on your own understanding; in all your ways acknowledge Him, and He shall direct your paths.', ref: 'Proverbs 3:5-6' },
    { text: 'Love suffers long and is kind; love does not envy; love does not parade itself, is not puffed up; does not behave rudely, does not seek its own, is not provoked, thinks no evil.', ref: '1 Corinthians 13:4-5' },
    { text: 'Your word is a lamp to my feet and a light to my path.', ref: 'Psalm 119:105' },
    { text: 'But seek first the kingdom of God and His righteousness, and all these things shall be added to you.', ref: 'Matthew 6:33' },
    { text: 'For God so loved the world that He gave His only begotten Son, that whoever believes in Him should not perish but have everlasting life.', ref: 'John 3:16' },
    { text: 'Jesus said to him: I am the way, the truth, and the life. No one comes to the Father except through Me.', ref: 'John 14:6' },
    { text: 'He who dwells in the secret place of the Most High shall abide under the shadow of the Almighty. I will say of the Lord: He is my refuge and my fortress; my God, in Him I will trust.', ref: 'Psalm 91:1-2' },
    { text: 'Therefore humble yourselves under the mighty hand of God, that He may exalt you in due time.', ref: '1 Peter 5:6' },
    { text: 'Casting all your care upon Him, for He cares for you.', ref: '1 Peter 5:7' },
    { text: 'I have been young, and now am old; yet I have not seen the righteous forsaken, nor his descendants begging bread.', ref: 'Psalm 37:25' },
    { text: 'Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth!', ref: 'Psalm 46:10' },
    { text: 'But with God all things are possible.', ref: 'Matthew 19:26' },
    { text: 'The Lord your God in your midst, the Mighty One, will save; He will rejoice over you with gladness, He will quiet you with His love, He will rejoice over you with singing.', ref: 'Zephaniah 3:17' },
    { text: 'Be strong and of good courage; do not be afraid, nor be dismayed, for the Lord your God is with you wherever you go.', ref: 'Joshua 1:9' },
    { text: 'What then shall we say to these things? If God is for us, who can be against us?', ref: 'Romans 8:31' },
    { text: 'Being confident of this very thing, that He who has begun a good work in you will complete it until the day of Jesus Christ.', ref: 'Philippians 1:6' },
    { text: 'Wait on the Lord; be of good courage, and He shall strengthen your heart; wait, I say, on the Lord!', ref: 'Psalm 27:14' },
    { text: 'The name of the Lord is a strong tower; the righteous run to it and are safe.', ref: 'Proverbs 18:10' },
    { text: 'The Lord is merciful and gracious, slow to anger, and abounding in mercy.', ref: 'Psalm 103:8' },
    { text: 'But those who wait on the Lord shall renew their strength; they shall mount up with wings like eagles, they shall run and not be weary, they shall walk and not faint.', ref: 'Isaiah 40:31' },
    { text: 'Blessed are the peacemakers, for they shall be called sons of God.', ref: 'Matthew 5:9' },
    { text: 'The Lord will fight for you, and you shall hold your peace.', ref: 'Exodus 14:14' },
    { text: 'In everything give thanks; for this is the will of God in Christ Jesus for you.', ref: '1 Thessalonians 5:18' },
    { text: 'And you shall know the truth, and the truth shall make you free.', ref: 'John 8:32' },
    { text: 'Therefore do not worry about tomorrow, for tomorrow will worry about its own things. Sufficient for the day is its own trouble.', ref: 'Matthew 6:34' }
  ]
};
